# Generated by Django 4.1.4 on 2022-12-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=30)),
                ('Patronymic', models.CharField(max_length=30)),
                ('Birthday', models.DateTimeField(verbose_name='birthday')),
            ],
        ),
        migrations.CreateModel(
            name='Kindergarten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('WorkDaysInWeek', models.IntegerField()),
                ('ChildrenNumber', models.IntegerField()),
                ('NominalSum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MonthAndYear', models.DateTimeField(verbose_name='monthAndYear')),
                ('WorkDaysNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=30)),
                ('Patronymic', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=13)),
                ('Comments', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='KindergartenGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChildrenNumber', models.IntegerField()),
                ('Name', models.CharField(max_length=30)),
                ('KindergartenID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten.kindergarten')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChildID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten.child')),
                ('ParentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten.parent')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='GroupID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten.kindergartengroup'),
        ),
        migrations.AddField(
            model_name='child',
            name='KindergartenID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten.kindergarten'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DaysAttended', models.IntegerField()),
                ('FinalSum', models.IntegerField()),
                ('ChildID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten.child')),
                ('MonthID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten.month')),
            ],
        ),
    ]
