# Generated by Django 4.1.4 on 2022-12-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAdditionInfo',
        ),
    ]
